### ISSUE TITLE
Support for more legend colors

### ISSUE THREAD

**Issue by mdn522** [mhansen/scatter.fm#38]
More colors if the user consents using toggle/checkbox

Distinct Colors Example:
https://sashamaps.net/docs/resources/20-colors/
https://en.wikipedia.org/wiki/Help:Distinguishable_colors

**Comment by mhansen** [comment]
I'd be ok with enabling more colors by default, as long as they're
distinguishable.

The relevant code to update is here:

https://github.com/mhansen/scatter.fm/blob/d7eb2ca82a6897a2b5eb36ae45b11e6611da3518/src/models/LegendModel.js#L3

I'm not really working on this project any more but would welcome pull
requests.

**Comment by mhansen** [comment]
I had another request recently:

> I would like to see more highlighted artists represented by a wider range of colors. Right now you color code 9 distinct artists (includer Other), when I think that figure could at least be doubled without losing too much clarity. For example, here are [23 colors](https://planetstar.fandom.com/wiki/Distinct_color_scheme) carefully selected to be “easy” to distinguish. [Another utility](https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12) offers 12 distinct colors, and [this one](https://medialab.github.io/iwanthue/) can create arbitrary numbers of colors, though I think 30 is about the upper limit of what I find separable. Of course, ease is subjective and this could decrease accessibility, though whatever expansion could be toggle-able.

**Comment by mhansen** [comment]
Fixed in 548739b79d4d682f3d3dc7f732b0e0c110fe5e30; we now show 12 colours.
